---
- name: Apply access management configurations
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml
    - organizations.yml
    - users.yml
    - teams.yml

  tasks:

    - name: Create/Update Organizations
      ansible.platform.organization:
        gateway_hostname: "https://automationgateway.home.lab"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: false
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        state: "{{ item.state }}"
      loop: "{{ aap_organizations }}"

    - name: Create/Update Users
      ansible.platform.user:
        gateway_hostname: "https://automationgateway.home.lab"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: false
        username: "{{ item.username }}"
        email: "{{ item.email }}"
        first_name: "{{ item.first_name }}"
        last_name: "{{ item.last_name }}"
        is_superuser: "{{ item.is_superuser }}"
        organizations: "{{ item.organizations }}"
        state: "{{ item.state }}"
      loop: "{{ aap_users }}"

    - name: Create/Update teams
      ansible.platform.team:
        gateway_hostname: "https://automationgateway.home.lab"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: false
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        state: "{{ item.state }}"
      loop: "{{ aap_teams }}"