---
- name: Rollback access management configurations
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yml
    - organizations.yml
    - users.yml
    - teams.yml

  environment:
    GATEWAY_HOSTNAME: "https://aap.home.lab"
    GATEWAY_USERNAME: "{{ gateway_username }}"
    GATEWAY_PASSWORD: "{{ gateway_password }}"
    GATEWAY_VERIFY_SSL: false

  tasks:

    - name: Rollback teams
      ansible.platform.team:
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        state: absent
      loop: "{{ aap_teams }}"

    - name: Rollback Users
      ansible.platform.user:
        username: "{{ item.username }}"
        state: absent
      loop: "{{ aap_users }}"

    - name: Rollback Organizations
      ansible.platform.organization:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ aap_organizations }}"
