---
- name: Configure AAP Access Management
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    gateway_host: "https://aap.home.lab"

  environment:
    GATEWAY_HOSTNAME: "{{ gateway_host }}"
    GATEWAY_USERNAME: "{{ gateway_username }}"
    GATEWAY_PASSWORD: "{{ gateway_password }}"
    GATEWAY_VERIFY_SSL: false
    CONTROLLER_HOST: "{{ gateway_host}}"
    CONTROLLER_USERNAME: "{{ gateway_username }}"
    CONTROLLER_PASSWORD: "{{ gateway_password }}"
    CONTROLLER_VERIFY_SSL: false

  vars_files:
    - vars/secrets.yml
    - vars/organizations.yml
    - vars/users.yml
    - vars/teams.yml
    - vars/team-roles.yml

  tasks:

    - name: Rollback teams
      ansible.platform.team:
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        state: absent
      loop: "{{ aap_teams }}"

    - name: Rollback Users
      ansible.platform.user:
        username: "{{ item.username }}"
        state: absent
      loop: "{{ aap_users }}"

    - name: Rollback Organizations
      ansible.platform.organization:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ aap_organizations }}"

...
