---
- name: Configure credentials
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../../secrets.yml
    - passwords.yml

  environment:
    CONTROLLER_HOST: "https://automationgateway.home.lab"
    CONTROLLER_USERNAME: "{{ gateway_username }}"
    CONTROLLER_PASSWORD: "{{ gateway_password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:

    - name: Machine credential
      ansible.controller.credential:
        name: AAP Admin
        description: AAP Administration credentials
        credential_type: Machine
        state: present
        user: admin
        inputs: 
          username: ansible
          password: "{{ machine_password }}"
