---
- name: Rollback credentials
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../../secrets.yml

  environment:
    CONTROLLER_HOST: "https://aap.home.lab"
    CONTROLLER_USERNAME: "{{ gateway_username }}"
    CONTROLLER_PASSWORD: "{{ gateway_password }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:

    - name: Remove machine credential
      ansible.controller.credential:
        name: AAP Admin
        credential_type: Machine
        state: absent
